export const citiesList = [
  "_Tunis",
  "Tunis",
  "Le Bardo",
  "Le Kram",
  "La Goulette",
  "Carthage",
  "Sidi Bou Said",
  "La Marsa",
  "Sidi Hassine",
  "_Ariana",
  "Ariana",
  "La Soukra",
  "Raoued",
  "Kalâat el-Andalous",
  "Sidi Thabet",
  "Ettadhamen",
  "Mnihla",
  "_Ben Arous",
  "Ben Arous",
  "El Mourouj",
  "Hammam Lif",
  "Hammam Chott",
  "Bou Mhel el-Bassatine",
  "Ezzahra",
  "Radès",
  "Mégrine",
  "Mohamedia",
  "Mornag",
  "Khalidia",
  "Fouchana",
  "Naassen",
  "_Manouba",
  "Manouba",
  "Den Den",
  "Douar Hicher",
  "Oued Ellil",
  "Mornaguia",
  "Borj El Amri",
  "Djedeida",
  "Tebourba",
  "El Battan",
  "_Nabeul",
  "Nabeul",
  "Dar Châabane El Fehri",
  "Béni Khiar",
  "El Maâmoura",
  "Somâa",
  "Korba",
  "Tazarka",
  "Menzel Temime",
  "Menzel Horr",
  "El Mida",
  "Kelibia",
  "Azmour",
  "Hammam Ghezèze",
  "Dar Allouch",
  "El Haouaria",
  "Takelsa",
  "Soliman",
  "Korbous",
  "Menzel Bouzelfa",
  "Béni Khalled",
  "Zaouiet Djedidi",
  "Grombalia",
  "Bou Argoub",
  "Hammamet",
  "Fondouk Jedid - Seltene",
  "Chrifet - Boucharray",
  "Sidi Djedidi",
  "Tazougrane - Boukrim - Zaouiet El Mgaies",
  "_Zaghouan",
  "Zaghouan",
  "Zriba",
  "Bir Mcherga",
  "Djebel Oust",
  "El Fahs",
  "Nadhour",
  "El Amaiem",
  "Saouaf",
  "_Bizerte",
  "Bizerte",
  "Sejnane",
  "Mateur",
  "Menzel Bourguiba",
  "Tinja",
  "Ghar al Milh",
  "Aousja",
  "Menzel Jemil",
  "Menzel Abderrahmane",
  "El Alia",
  "Ras Jebel",
  "Metline",
  "Raf Raf",
  "El Hachachna",
  "Ghezala",
  "Joumine",
  "Utique",
  "_Béja",
  "Béja",
  "El Maâgoula",
  "Zahret Medien",
  "Nefza",
  "Téboursouk",
  "Testour",
  "Goubellat",
  "Medjez El Bab",
  "Ouchtata - Jmila",
  "Sidi Ismaïl",
  "Slouguia",
  "Thibar",
  "_Jendouba",
  "Jendouba",
  "Bou Salem",
  "Tabarka",
  "Aïn Draham",
  "Fernana",
  "Beni M'Tir",
  "Ghardimaou",
  "Oued Melliz",
  "Jouaouda",
  "Souk Sebt",
  "Kalaa - Maaden - Farksan",
  "Khmairia",
  "Aïn Sobh - Nadhour",
  "Balta - Bou Aouane",
  "_Kef",
  "El Kef",
  "Nebeur",
  "Touiref",
  "Sakiet Sidi Youssef",
  "Tajerouine",
  "Menzel Salem",
  "Kalaat Senan",
  "Kalâat Khasba",
  "Jérissa",
  "El Ksour",
  "Dahmani",
  "Sers",
  "Bahra",
  "El Marja",
  "Zaafrane - Dir Kef",
  "_Siliana",
  "Siliana",
  "Bou Arada",
  "Gaâfour",
  "El Krib",
  "Sidi Bou Rouis",
  "Maktar",
  "Rouhia",
  "Kesra",
  "Bargou",
  "El Aroussa",
  "El Hababsa",
  "Sidi Morched",
  "_Sousse",
  "Sousse",
  "Ksibet Thrayet",
  "Ezzouhour",
  "Zaouiet Sousse",
  "Hammam Sousse",
  "Akouda",
  "Kalâa Kebira",
  "Sidi Bou Ali",
  "Hergla",
  "Enfidha",
  "Bouficha",
  "Sidi El Hani",
  "M'saken",
  "Kalâa Seghira",
  "Messaadine",
  "Kondar",
  "Chott Meriem",
  "Grimet - Hicher",
  "_Monastir",
  "Monastir",
  "Khniss",
  "Ouerdanine",
  "Sahline Moôtmar",
  "Sidi Ameur",
  "Zéramdine",
  "Beni Hassen",
  "Ghenada",
  "Jemmal",
  "Menzel Kamel",
  "Zaouiet Kontoch",
  "Bembla-Mnara",
  "Menzel Ennour",
  "El Masdour",
  "Moknine",
  "Sidi Bennour",
  "Menzel Fersi",
  "Amiret El Fhoul",
  "Amiret Touazra",
  "Amiret Hajjaj",
  "Cherahil",
  "Bekalta",
  "Téboulba",
  "Ksar Hellal",
  "Ksibet El Mediouni",
  "Bennane Bodheur",
  "Touza",
  "Sayada",
  "Lemta",
  "Bouhjar",
  "Menzel Hayet",
  "_Mahdia",
  "Mahdia",
  "Rejiche",
  "Bou Merdes",
  "Ouled Chamekh",
  "Chorbane",
  "Hebira",
  "Essouassi",
  "El Djem",
  "Kerker",
  "Chebba",
  "Melloulèche",
  "Sidi Alouane",
  "Ksour Essef",
  "El Bradâa",
  "El Hekaima",
  "Sidi Zid - Awled Moulahem",
  "Tlelsa",
  "Zelba",
  "_Sfax",
  "Sfax",
  "Sakiet Ezzit",
  "Chihia",
  "Sakiet Eddaïer",
  "Gremda",
  "El Aïn",
  "Thyna",
  "Agareb",
  "Jebiniana",
  "El Hencha",
  "Menzel Chaker",
  "Ghraïba",
  "Bir Ali Ben Khalifa",
  "Skhira",
  "Mahares",
  "Kerkennah",
  "El Achech",
  "El Amra",
  "El Nasr",
  "Hadjeb",
  "Hazeg - Ellouza",
  "Nadhour - Sidi Ali Ben Abed",
  "Ouabed - Khazanet",
  "El Ghraiba",
  "Sidi Salah",
  "Bir Ali Ben Khalifa Rural",
  "_Kairouan",
  "Kairouan",
  "Chebika",
  "Sbikha",
  "Oueslatia",
  "Aïn Djeloula",
  "Haffouz",
  "El Alâa",
  "Hajeb El Ayoun",
  "Nasrallah",
  "Menzel Mehiri",
  "Echrarda",
  "Bou Hajla",
  "Raqqada",
  "Chraitia - Ksour",
  "Sisseb - Driaat",
  "Jehina",
  "Aïn El Beïdha",
  "Chaouachi",
  "Abida",
  "Sbikha Est",
  "_Kasserine",
  "Kasserine",
  "Sbeitla",
  "Sbiba",
  "Jedelienne",
  "Thala",
  "Haïdra",
  "Foussana",
  "Fériana",
  "Thélepte",
  "Magel Bel Abbès",
  "_Sidi Bouzid",
  "Sidi Bouzid",
  "Jilma",
  "Cebbala Ouled Asker",
  "Bir El Hafey",
  "Sidi Ali Ben Aoun",
  "Menzel Bouzaiane",
  "Meknassy",
  "Mezzouna",
  "Regueb",
  "Ouled Haffouz",
  "Souk Jedid",
  "Sidi Bouzid Ouest",
  "Sidi Bouzid Est",
  "El Hichria",
  "_Gabès",
  "Gabès",
  "Chenini Nahal",
  "Ghannouch",
  "Métouia",
  "Oudhref",
  "El Hamma",
  "Matmata",
  "Nouvelle Matmata",
  "Mareth",
  "Zarat",
  "Teboulbou",
  "Habib Thameur Bouatouch",
  "Kettana",
  "Bouchemma",
  "Dkhilet Toujane",
  "Menzel El Habib",
  "_Medenine",
  "Medenine",
  "Beni Khedache",
  "Ben Gardane",
  "Zarzis",
  "Houmt El Souk",
  "Midoun",
  "Ajim",
  "Sidi Makhlouf",
  "_Tataouine",
  "Tataouine",
  "Bir Lahmar",
  "Ghomrassen",
  "Dehiba",
  "Remada",
  "Smâr",
  "_Gafsa",
  "Gafsa",
  "El Ksar",
  "Moularès",
  "Redeyef",
  "Métlaoui",
  "Mdhila",
  "El Guettar",
  "Sened",
  "Belkhir",
  "Lalla",
  "Sidi Aïch",
  "Sidi Boubaker",
  "Zannouch",
  "_Tozeur",
  "Tozeur",
  "Degache",
  "El Hamma du Jérid",
  "Nafta",
  "Tamerza",
  "Hazoua",
  "_Kebili",
  "Kebili",
  "Djemna",
  "Douz",
  "El Golâa",
  "Souk Lahad",
  "Bechli - Blidet - Jerssin",
  "Bechri - Fatnassa",
  "Faouar",
  "Rjim Maatoug"
]