// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​u​y​e​r
	 */
	BUYER: string
	/**
	 * S​e​l​l​e​r
	 */
	SELLER: string
	/**
	 * C​o​u​r​i​e​r
	 */
	COURIER: string
}

export type TranslationFunctions = {
	/**
	 * Buyer
	 */
	BUYER: () => LocalizedString
	/**
	 * Seller
	 */
	SELLER: () => LocalizedString
	/**
	 * Courier
	 */
	COURIER: () => LocalizedString
}

export type Formatters = {}
