// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​u​y​e​r
	 */
	BUYER: string
	/**
	 * S​e​l​l​e​r
	 */
	SELLER: string
	/**
	 * C​o​u​r​i​e​r
	 */
	COURIER: string
	/**
	 * C​r​e​a​t​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	SIGNUP_TITLE: string
	/**
	 * J​o​i​n​ ​o​u​r​ ​m​a​r​k​e​t​p​l​a​c​e​ ​i​n​ ​j​u​s​t​ ​a​ ​f​e​w​ ​s​t​e​p​s
	 */
	SIGNUP_SUBTITLE: string
	/**
	 * R​o​l​e
	 */
	STEP_ROLE: string
	/**
	 * P​r​o​f​i​l​e
	 */
	STEP_PROFILE: string
	/**
	 * D​e​t​a​i​l​s
	 */
	STEP_DETAILS: string
	/**
	 * W​h​a​t​ ​b​r​i​n​g​s​ ​y​o​u​ ​h​e​r​e​?
	 */
	ROLE_STEP_TITLE: string
	/**
	 * C​h​o​o​s​e​ ​t​h​e​ ​r​o​l​e​ ​t​h​a​t​ ​b​e​s​t​ ​f​i​t​s​ ​y​o​u​r​ ​n​e​e​d​s
	 */
	ROLE_STEP_SUBTITLE: string
	/**
	 * B​r​o​w​s​e​ ​a​n​d​ ​p​u​r​c​h​a​s​e​ ​p​r​o​d​u​c​t​s
	 */
	BUYER_DESC: string
	/**
	 * L​i​s​t​ ​a​n​d​ ​s​e​l​l​ ​y​o​u​r​ ​o​f​f​e​r​i​n​g​s
	 */
	SELLER_DESC: string
	/**
	 * D​e​l​i​v​e​r​ ​o​r​d​e​r​s​ ​a​c​r​o​s​s​ ​c​i​t​i​e​s
	 */
	COURIER_DESC: string
	/**
	 * P​e​r​s​o​n​a​l​ ​i​n​f​o​r​m​a​t​i​o​n
	 */
	PROFILE_STEP_TITLE: string
	/**
	 * T​e​l​l​ ​u​s​ ​a​ ​b​i​t​ ​a​b​o​u​t​ ​y​o​u​r​s​e​l​f
	 */
	PROFILE_STEP_SUBTITLE: string
	/**
	 * F​i​r​s​t​ ​n​a​m​e
	 */
	FIRST_NAME: string
	/**
	 * J​o​h​n
	 */
	FIRST_NAME_PLACEHOLDER: string
	/**
	 * L​a​s​t​ ​n​a​m​e
	 */
	LAST_NAME: string
	/**
	 * D​o​e
	 */
	LAST_NAME_PLACEHOLDER: string
	/**
	 * P​h​o​n​e​ ​n​u​m​b​e​r
	 */
	PHONE_NUMBER: string
	/**
	 * +​2​1​6​ ​X​X​ ​X​X​X​ ​X​X​X
	 */
	PHONE_NUMBER_PLACEHOLDER: string
	/**
	 * d​e​t​a​i​l​s
	 */
	DETAILS_STEP_TITLE_SUFFIX: string
	/**
	 * J​u​s​t​ ​a​ ​f​e​w​ ​m​o​r​e​ ​d​e​t​a​i​l​s​ ​t​o​ ​c​o​m​p​l​e​t​e​ ​y​o​u​r​ ​p​r​o​f​i​l​e
	 */
	DETAILS_STEP_SUBTITLE: string
	/**
	 * R​e​s​i​d​e​n​c​e
	 */
	RESIDENCE: string
	/**
	 * Y​o​u​r​ ​c​i​t​y​ ​o​r​ ​a​d​d​r​e​s​s
	 */
	RESIDENCE_PLACEHOLDER: string
	/**
	 * S​e​r​v​i​c​e​ ​t​y​p​e
	 */
	SERVICE_TYPE: string
	/**
	 * S​e​r​v​i​c​e
	 */
	SERVICE_TYPE_SERVICE: string
	/**
	 * L​a​b​o​u​r
	 */
	SERVICE_TYPE_LABOUR: string
	/**
	 * P​r​o​d​u​c​t
	 */
	SERVICE_TYPE_PRODUCT: string
	/**
	 * T​i​t​l​e
	 */
	SERVICE_TITLE: string
	/**
	 * e​.​g​.​ ​P​r​o​f​e​s​s​i​o​n​a​l​ ​P​l​u​m​b​e​r
	 */
	SERVICE_TITLE_PLACEHOLDER: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	SERVICE_DESCRIPTION: string
	/**
	 * B​r​i​e​f​l​y​ ​d​e​s​c​r​i​b​e​ ​w​h​a​t​ ​y​o​u​ ​o​f​f​e​r​.​.​.
	 */
	SERVICE_DESCRIPTION_PLACEHOLDER: string
	/**
	 * W​o​r​k​i​n​g​ ​c​i​t​i​e​s
	 */
	WORKING_CITIES: string
	/**
	 * T​y​p​e​ ​a​ ​c​i​t​y​ ​a​n​d​ ​p​r​e​s​s​ ​E​n​t​e​r
	 */
	WORKING_CITIES_PLACEHOLDER: string
	/**
	 * P​r​e​s​s​ ​E​n​t​e​r​ ​t​o​ ​a​d​d​ ​a​ ​c​i​t​y
	 */
	WORKING_CITIES_HINT: string
	/**
	 * R​e​m​o​v​e​ ​{​c​i​t​y​}
	 * @param {string} city
	 */
	REMOVE_CITY: RequiredParams<'city'>
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * C​o​n​t​i​n​u​e
	 */
	CONTINUE: string
	/**
	 * F​i​n​i​s​h
	 */
	FINISH: string
	/**
	 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
	 */
	ALREADY_HAVE_ACCOUNT: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
}

export type TranslationFunctions = {
	/**
	 * Buyer
	 */
	BUYER: () => LocalizedString
	/**
	 * Seller
	 */
	SELLER: () => LocalizedString
	/**
	 * Courier
	 */
	COURIER: () => LocalizedString
	/**
	 * Create your account
	 */
	SIGNUP_TITLE: () => LocalizedString
	/**
	 * Join our marketplace in just a few steps
	 */
	SIGNUP_SUBTITLE: () => LocalizedString
	/**
	 * Role
	 */
	STEP_ROLE: () => LocalizedString
	/**
	 * Profile
	 */
	STEP_PROFILE: () => LocalizedString
	/**
	 * Details
	 */
	STEP_DETAILS: () => LocalizedString
	/**
	 * What brings you here?
	 */
	ROLE_STEP_TITLE: () => LocalizedString
	/**
	 * Choose the role that best fits your needs
	 */
	ROLE_STEP_SUBTITLE: () => LocalizedString
	/**
	 * Browse and purchase products
	 */
	BUYER_DESC: () => LocalizedString
	/**
	 * List and sell your offerings
	 */
	SELLER_DESC: () => LocalizedString
	/**
	 * Deliver orders across cities
	 */
	COURIER_DESC: () => LocalizedString
	/**
	 * Personal information
	 */
	PROFILE_STEP_TITLE: () => LocalizedString
	/**
	 * Tell us a bit about yourself
	 */
	PROFILE_STEP_SUBTITLE: () => LocalizedString
	/**
	 * First name
	 */
	FIRST_NAME: () => LocalizedString
	/**
	 * John
	 */
	FIRST_NAME_PLACEHOLDER: () => LocalizedString
	/**
	 * Last name
	 */
	LAST_NAME: () => LocalizedString
	/**
	 * Doe
	 */
	LAST_NAME_PLACEHOLDER: () => LocalizedString
	/**
	 * Phone number
	 */
	PHONE_NUMBER: () => LocalizedString
	/**
	 * +216 XX XXX XXX
	 */
	PHONE_NUMBER_PLACEHOLDER: () => LocalizedString
	/**
	 * details
	 */
	DETAILS_STEP_TITLE_SUFFIX: () => LocalizedString
	/**
	 * Just a few more details to complete your profile
	 */
	DETAILS_STEP_SUBTITLE: () => LocalizedString
	/**
	 * Residence
	 */
	RESIDENCE: () => LocalizedString
	/**
	 * Your city or address
	 */
	RESIDENCE_PLACEHOLDER: () => LocalizedString
	/**
	 * Service type
	 */
	SERVICE_TYPE: () => LocalizedString
	/**
	 * Service
	 */
	SERVICE_TYPE_SERVICE: () => LocalizedString
	/**
	 * Labour
	 */
	SERVICE_TYPE_LABOUR: () => LocalizedString
	/**
	 * Product
	 */
	SERVICE_TYPE_PRODUCT: () => LocalizedString
	/**
	 * Title
	 */
	SERVICE_TITLE: () => LocalizedString
	/**
	 * e.g. Professional Plumber
	 */
	SERVICE_TITLE_PLACEHOLDER: () => LocalizedString
	/**
	 * Description
	 */
	SERVICE_DESCRIPTION: () => LocalizedString
	/**
	 * Briefly describe what you offer...
	 */
	SERVICE_DESCRIPTION_PLACEHOLDER: () => LocalizedString
	/**
	 * Working cities
	 */
	WORKING_CITIES: () => LocalizedString
	/**
	 * Type a city and press Enter
	 */
	WORKING_CITIES_PLACEHOLDER: () => LocalizedString
	/**
	 * Press Enter to add a city
	 */
	WORKING_CITIES_HINT: () => LocalizedString
	/**
	 * Remove {city}
	 */
	REMOVE_CITY: (arg: { city: string }) => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * Continue
	 */
	CONTINUE: () => LocalizedString
	/**
	 * Finish
	 */
	FINISH: () => LocalizedString
	/**
	 * Already have an account?
	 */
	ALREADY_HAVE_ACCOUNT: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
}

export type Formatters = {}
